/*
 * Generated by ISE 15.01.9.6535 GPL Edition - linux-x86
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F218_6166();
extern void F220_6319();
extern void F225_6388();
extern void F226_6527();
extern void F250_3494();
extern void F242_6047();
extern void F111_1569();
extern EIF_REFERENCE F111_1556();
extern EIF_BOOLEAN F111_1568();
extern EIF_BOOLEAN F111_1573();
extern void F111_1578();
extern void F111_1579();
extern void F111_1580();
extern void F44_1099();
extern EIF_TYPED_VALUE F44_1100();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F218_6166;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F225_6388;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F250_3494;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F220_6319;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F226_6527;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F242_6047;
#ifdef RTS_SCP_CAPABLE
	egc_is_scoop_capable = 0;
#endif
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F111_1569;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F111_1568;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F111_1556;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F111_1573;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F111_1578;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F111_1579;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F111_1580;

	egc_str_dtype = 219;

	egc_str32_dtype = 225;
	egc_arr_dtype = 249;
	egc_tup_dtype = 173;
	egc_disp_rout_id = 2653;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = (EIF_TYPE_INDEX)552;
	egc_sp_wchar = (EIF_TYPE_INDEX)788;
	egc_sp_bool = (EIF_TYPE_INDEX)387;
	egc_sp_uint8 = (EIF_TYPE_INDEX)713;
	egc_sp_uint16 = (EIF_TYPE_INDEX)680;
	egc_sp_uint32 = (EIF_TYPE_INDEX)422;
	egc_sp_uint64 = (EIF_TYPE_INDEX)439;
	egc_sp_int8 = (EIF_TYPE_INDEX)511;
	egc_sp_int16 = (EIF_TYPE_INDEX)750;
	egc_sp_int32 = (EIF_TYPE_INDEX)293;
	egc_sp_int64 = (EIF_TYPE_INDEX)643;
	egc_sp_real32 = (EIF_TYPE_INDEX)587;
	egc_sp_real64 = (EIF_TYPE_INDEX)324;
	egc_sp_pointer = (EIF_TYPE_INDEX)475;
	egc_sp_ref = (EIF_TYPE_INDEX)242;

	egc_uint8_dtype = 193;
	egc_uint16_dtype = 202;
	egc_uint32_dtype = 199;
	egc_uint64_dtype = 211;
	egc_int8_dtype = 175;
	egc_int16_dtype = 208;
	egc_int32_dtype = 205;
	egc_int64_dtype = 184;
	egc_bool_dtype = 187;
	egc_real32_dtype = 196;
	egc_char_dtype = 181;
	egc_wchar_dtype = 178;
	egc_real64_dtype = 190;
	egc_point_dtype = 214;
#ifdef RTS_SCP_CAPABLE
#if RTS_SCP_CAPABLE == 1
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#else
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#endif
#endif

	egc_exception_dtype = 60;
	egc_except_emnger_dtype = 110;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "memcache";
	egc_system_location = "/home/lara/Documents/SA/memcache/EIFGENs/memcache/W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1434119150;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 975;

	egc_rcount = 3;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 5653;
	egc_rcarg[0] = 0;
	
	egc_rlist[1] = "EQA_EVALUATOR.make";
	egc_rcdt[1] = 0;
	egc_rcrid[1] = 5664;
	egc_rcarg[1] = 0;
	
	egc_rlist[2] = "ITP_INTERPRETER.execute";
	egc_rcdt[2] = 0;
	egc_rcrid[2] = 6277;
	egc_rcarg[2] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 43;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F44_1099;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F44_1100;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 924; /* APPLICATION */
	}if (egc_rcdt[1] == 0) {
		egc_rcdt[1] = 929; /* EQA_EVALUATOR */
	}if (egc_rcdt[2] == 0) {
		egc_rcdt[2] = 972; /* ITP_INTERPRETER */
	}
}

#ifdef __cplusplus
}
#endif
